services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lambda_twist_api
    ports:
      - "${API_PORT:-8001}:${API_PORT:-8001}"
    env_file:
      - .env
    volumes:
      - ./application_default_credentials.json:/app/application_default_credentials.json:ro
    develop:
      watch:
        - path: ./src
          action: sync+restart
          target: /app/src
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/application_default_credentials.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:${API_PORT:-8001}/api/v1/general/health"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    command: /app/.venv/bin/python -m uvicorn src.LambdaTwist.main:app --host 0.0.0.0 --port ${API_PORT:-8001} --reload --app-dir /app

  slackbot:
    build:
      context: ./Slackbot
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      API_URL: http://api:${API_PORT:-8001}
    volumes:
      - /app/.venv
    develop:
      watch:
        - path: ./Slackbot
          action: sync
          target: /app
          ignore:
            - "**/__pycache__"
            - "**/*.pyc"
    depends_on:
      api:
        condition: service_healthy
