# Build stage
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder

# Set working directory
WORKDIR /app

# Install UV from official image
COPY --from=ghcr.io/astral-sh/uv:0.6.14 /uv /bin/uv

# Copy the requirements.txt into the container
COPY requirements.txt ./

# Create and activate the uv virtual environment
RUN uv venv /app/.uvenv  # Creates a new virtual environment inside the container
RUN . /app/.uvenv/bin/activate && uv pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Copy the entrypoint_sync.sh script into the container
RUN chmod +x /app/entrypoint_sync.sh

# Set environment variables
ENV PYTHONPATH=/app

# Set the entrypoint to the entrypoint_sync.sh script
ENTRYPOINT ["/app/entrypoint_sync.sh"]

## debugging
# CMD ["/bin/bash"]